### ISSUE TITLE
Omniauth with 3.1

### ISSUE THREAD

**Issue by dbkbali** [RailsApps/rails3-mongoid-omniauth#1]
Daniel,

Wondering whether you have tested this app with 3.1 ? 

I am in the process of migrating an app from 3.0.8 to 3.1rc1 and am having some problems. However this app also incorporates Devise. I need to complete some further investigation to determine whether this is an omniauth/rails 3.1rc issue, or the integration of Devise with Omniauth  is causing problems. The error message I am getting is:

/Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:237:in `require': no such file to load -- omniauth/password (LoadError)
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:237:in`block in require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:639:in`new_constants_in'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0.rc1/lib/active_support/dependencies.rb:237:in`require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/omniauth-0.0.1/lib/omniauth.rb:4:in `block in <top (required)>'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/omniauth-0.0.1/lib/omniauth.rb:3:in`each'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/omniauth-0.0.1/lib/omniauth.rb:3:in `<top (required)>'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in`require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in`each'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in `block in require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in`each'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in `require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@global/gems/bundler-1.0.13/lib/bundler.rb:120:in`require'
    from /Users/dbk/Development/what2do.base/config/application.rb:12:in `<top (required)>'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc1/lib/rails/commands.rb:52:in`require'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc1/lib/rails/commands.rb:52:in `block in <top (required)>'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc1/lib/rails/commands.rb:49:in`tap'
    from /Users/dbk/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc1/lib/rails/commands.rb:49:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Everything worked well in 3.0.8 (Devise and Omniauth and Mongoid - combining your approach in the sample apps with the railscasts approach), will update once I have completed further investigation. Obviously if you can confirm that your app works with just Omniauth in 3.1 then I can eliminate one point of investigation.

Thanks

David

**Comment by fortuity** [comment]
For an Omniauth and Mongoid example app that works with Rails 3.1, use the application template in the repo https://github.com/RailsApps/rails3-application-templates to generate a new app. I recently updated the application template to create a Rails 3.1 app and it's been tested. I'll be updating the example app repo in the next few days.

You closed the issue... did you get your problem resolved?

-- Daniel

**Comment by dbkbali** [comment]
Daniel,

Yes I decided to rebuild the app from the ground up with your composer gem which worked great. Only problem was that I had an older version of tilt installed and the recipe wouldn't complete the first time until I removed it. Anyway great gem! If I had more time and it hasnt been done I will try and contribute later ie. Thanks for the help.

David

**Comment by TriKro** [comment]
I seem to be running into the same issue, but I didn't quite understand the fix. I would prefer not to rebuild my app from the ground up. Can you explain further what the issue was?

Thanks,
Tristan

**Comment by dbkbali** [comment]
If I recall this issue correctly you need to delete any locally stored version of tilt before using the composer gem which may have dependencies on a newer version of tilt

**Comment by TriKro** [comment]
Thanks! I reinstalled the ruby and the gems entirely and that seems to have done the trick.

Cheers.
