### ISSUE TITLE
Trying to create the app with the template fails

### ISSUE THREAD

**Issue by novito** [RailsApps/rails3-mongoid-omniauth#13]
I'm trying to create the app by using the template and I keep getting "$ Command not found" - I've tried with the omniauth template and is working as expected. Refer to http://stackoverflow.com/questions/9369655/command-not-found-with-rails-new-app-m-myfile-rb

Thanks

**Comment by DanielKehoe** [comment]
The "$" you see at the beginning of the command is actually a convention that indicates a Unix console prompt. Don't include the "$".
