### ISSUE TITLE
rake db:migrate does not run

### ISSUE THREAD

**Issue by yuvalkarmi** [RailsApps/rails3-mongoid-omniauth#2]
When installing the app, running `rake db:migrate` or `bundle exec rake db:migrate` does not work.
After following some comments on StackOverflow, I added `gem 'rake', '0.8.7'` to my gemfile and ran `bundle update` but neither commands work. The error I am getting is:

rake aborted!
Don't know how to build task 'db:migrate'

I am using 3.1.0.rc1.

**Comment by fortuity** [comment]
When you use Mongoid and MongoDB, there is no need to run `rake db:migrate`. An advantage of using MongoDB is there is no need for migrations or schemas. The example app README and tutorial does not mention `rake db:migrate`. What is the reason you are trying to use `rake db:migrate`? A misunderstanding? Or are you attempting to use ActiveRecord in combination with Mongoid for access to multiple databases?

-- Daniel
