### ISSUE TITLE
email from twitter is blank

### ISSUE THREAD

**Issue by regmiprem** [RailsApps/rails3-mongoid-omniauth#20]
I did omniauth by looking this app. It works for me for linkdin and facebook. But it doesnot fetch email address for twitter. 

 Is it possible to login that user with same facebook username and password again by not calling api  once he call api before . I mean to say with same password he use in his facebook,linkdin,twitter inside devise login.

**Comment by MarkDBlackwell** [comment]
The users' email address has never been supplied by Twitter's [authentication](https://dev.twitter.com/docs/auth/oauth) service. The RailsApps documentation gives more explanation under "[The Email Problem](https://github.com/RailsApps/rails3-mongoid-omniauth#the-email-problem)."
