### ISSUE TITLE
slim template

### ISSUE THREAD

**Issue by danil-z** [RailsApps/rails3-mongoid-omniauth#21]
Hello. i've tried composer omniauth with mongoid recipe using slim template handler choise

rails new dummy -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb -T -O
cd dummy
rails s

and got an error :

``` ruby
Slim::Parser::SyntaxError at /
Expected attribute
  /Users/danil/Sites/autoservice61/app/views/layouts/application.html.slim, Line 11, Column 7
    body{:class => "#{controller_name} # action_name}"
```

_Request info_

``` ruby
Request parameters  
{"controller"=>"home", "action"=>"index"}
Rack session    
#<Rack::Session::Abstract::SessionHash:0x3fe72e9f4c28 not yet loaded>
```

**Comment by DanielKehoe** [comment]
Yes, I'm seeing errors when the app is generated with the Slim option. Could be a problem with the haml2slim gem. Unfortunately I've often seen problems when converting the view files to Slim so I consider the Slim option "experimental."
