### ISSUE TITLE
In docs, the Meetup OmniAuth provider also lacks email

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-omniauth#27]
In section [The Email Problem](https://github.com/RailsApps/rails3-mongoid-omniauth#the-email-problem), (if you want to) you might add Meetup to the list of providers not supplying an email address for the user, as in:

"And other service providers do not provide the email address at all (LinkedIn, Meetup, Twitter)."

Here's a [reference](http://markdblackwell.blogspot.com/2013/04/meetup-authentication-email-addresses.html) for more information (and it contains a link back to your site).

**Comment by DanielKehoe** [comment]
Thanks. Done.
