### ISSUE TITLE
In tutorial, Markus Proske's links moved

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails3-mongoid-omniauth#28]
In the tutorial under 'Similar Examples and Tutorials', Markus Proske's links aren't working anymore. Currently they reside on [https://communityguides.heroku.com](https://communityguides.heroku.com), apparently.

I found the '[OmniAuth Pure](https://communityguides.heroku.com/articles/16)' tutorial there, as well as the '[Devise and OmniAuth](https://communityguides.heroku.com/articles/11)' tutorial you had linked to, perhaps.

**Comment by DanielKehoe** [comment]
Fixed. Thank you.
