### ISSUE TITLE
rails3-mongoid-omniauth option gone

### ISSUE THREAD

**Issue by kellyguire** [RailsApps/rails3-mongoid-omniauth#32]
It appears that the options for $ rails new rails3-mongoid-omniauth -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb -T -O   have been changed and none of them lead to the rails3-mongoid-omniauth. Is there another way to follow the application/tutorial?

**Comment by DanielKehoe** [comment]
The current version of the example is written for Rails 3.2. If you use the Rails Composer with Rails 3.2, you will have the option described.
