### ISSUE TITLE
Attributes of an Object

### ISSUE THREAD

**Issue by Umair** [RailsApps/rails3-mongoid-omniauth#4]
There is function of attributes_name in Active record by which I can check the keys of an object but I can check the blank keys for of an object which is of MongoID not of ActiveRecord, When I try this I got the following response

ruby-1.9.2-p290 :001 > u = User.new
User _id: 4e684f7771393161cc000001, _type: nil, username: nil, first_name: nil, last_name: nil, email: nil, password: nil, password_salt: nil, password_hash: nil, profile_picture: nil, facebook_id: nil, facebook_enabled: nil, facebook_access_token: nil, twitter_id: nil, twitter_enabled: nil, twitter_access_token: nil, twitter_access_secret: nil, points: nil, remember_token: nil, remember_token_expires_at: nil, active: false, activation_code: nil, activated_at: nil
ruby-1.9.2-p290 :002 > u.attributes.keys
=> ["active", "_id"]

**Comment by DanielKehoe** [comment]
If I understand your question, it is not an issue specific to the rails3-mongoid-omniauth example app. Rather, it is general to Mongoid. You should ask the question on the Mongoid mailing list (Google group): http://groups.google.com/group/mongoid?hl=en

I am closing the issue but feel free to reopen it if I did not understand your question.

-- Daniel
