### ISSUE TITLE
Fails if you choose Other for OmniAuth Provider

### ISSUE THREAD

**Issue by billc** [RailsApps/rails3-mongoid-omniauth#8]
Received the below error when I choose Other for OmniAuth Provider. Re-ran and choose Twitter and the script completed without incident.

home_page  HomePage recipe running 'after bundler'
      remove    public/index.html
    generate    controller
/Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/omniauth-1.0.0/lib/omniauth/builder.rb:22:in `const_get': uninitialized constant OmniAuth::Strategies::Provider (NameError)
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/omniauth-1.0.0/lib/omniauth/builder.rb:22:in`provider'
    from /Users/billc/Projects/goblin/config/initializers/omniauth.rb:2:in `block in <top (required)>'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/rack-1.3.5/lib/rack/builder.rb:51:in`instance_eval'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/rack-1.3.5/lib/rack/builder.rb:51:in `initialize'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/omniauth-1.0.0/lib/omniauth/builder.rb:7:in`initialize'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:43:in `new'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:43:in`build'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:112:in `block in build'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:112:in`each'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:112:in `inject'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/actionpack-3.1.1/lib/action_dispatch/middleware/stack.rb:112:in`build'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/engine.rb:447:in `app'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/application/finisher.rb:37:in`block in module:Finisher'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/initializable.rb:30:in`run'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/initializable.rb:54:in`each'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/application.rb:96:in`initialize!'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/billc/Projects/goblin/config/environment.rb:5:in`<top (required)>'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/application.rb:83:in `require'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/application.rb:83:in`require_environment!'
    from /Users/billc/.rvm/gems/ruby-1.9.2-p290@goblin/gems/railties-3.1.1/lib/rails/commands.rb:22:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'
      remove    app/views/home/index.html.haml
      create    app/views/home/index.html.haml
        gsub    config/routes.rb
  home_page_users  HomePageUsers recipe running 'after bundler'
        gsub    app/controllers/home_controller.rb
The template [https://github.com/RailsApps/rails3-application-templates/raw/master/rails3-mongoid-omniauth-template.rb] could not be loaded. Error: No such file or directory - /Users/billc/Projects/goblin/app/controllers/home_controller.rb

**Comment by DanielKehoe** [comment]
This issue has been corrected in the newest version. Thanks for pointing this out. Seems the best way to address the issue is removing "other" as an option since OmniAuth needs a provider installed.
